// @ts-nocheck
// Generated by pnpm functions:bundle. Edit the canonical source, then regenerate.
// Function name: flight-api
// Source SHA-256: 11b73eeeb5d8af96b4753e83dc1ec21b270d978c01d16de7316a377fd66a27e4
// Uses server-side authentication. Deploy with verify_jwt=false as documented.
import { createClient } from "npm:@supabase/supabase-js@2.116.0";
import { z } from "npm:zod@3.25.76";
//#region supabase/functions/_shared/safety.ts
/** Additive v1 telemetry extension. Missing fields never mean healthy. */
var safetySchema = z.object({
	schemaVersion: z.literal(1),
	flightFailure: z.boolean().nullable(),
	failureReason: z.string().max(250).nullable(),
	readyForTakeoff: z.boolean().nullable(),
	parachute: z.object({
		installed: z.boolean().nullable(),
		ready: z.boolean().nullable(),
		state: z.enum([
			"unknown",
			"stowed",
			"released",
			"deployed",
			"fault"
		]),
		feedback: z.enum([
			"none",
			"release_sensor",
			"deployment_sensor"
		])
	}).nullable()
});
//#endregion
//#region supabase/functions/_shared/modes.ts
var neutral = {
	leftAileron: 0,
	rightAileron: 0,
	elevator: 0,
	rudder: 0
};
var finite = z.number().finite();
var anglesSchema = z.object({
	leftAileron: finite.min(-45).max(45),
	rightAileron: finite.min(-45).max(45),
	elevator: finite.min(-45).max(45),
	rudder: finite.min(-45).max(45)
});
var preset = z.object({
	angles: anglesSchema,
	transitionSeconds: finite.min(1).max(15)
});
var modeSchema = z.object({
	version: z.number().int().positive(),
	presets: z.object({
		cruise: preset,
		takeoff: preset,
		landing: preset
	}),
	travelDegrees: z.object({
		leftAileron: finite.min(1).max(45),
		rightAileron: finite.min(1).max(45),
		elevator: finite.min(1).max(45),
		rudder: finite.min(1).max(45)
	}),
	maxDegreesPerSecond: finite.min(1).max(30),
	startup: z.object({
		enabled: z.boolean(),
		delaySeconds: z.literal(5),
		amplitudeDegrees: finite.min(1).max(10)
	})
});
({ ...neutral }), { ...neutral }, { ...neutral };
//#endregion
//#region supabase/functions/_shared/contracts.ts
var n = z.number().finite(), nullable = n.nullable(), id = z.string().min(1).max(80).regex(/^[A-Za-z0-9_-]+$/), bool = z.boolean().nullable();
var channelSchema = z.object({
	name: z.string().min(1).max(60),
	min: n.min(750).max(2250),
	center: n.min(750).max(2250),
	max: n.min(750).max(2250),
	reverse: z.boolean(),
	deadband: n.min(0).max(.2),
	trim: n.min(-.3).max(.3),
	subtrim: n.min(-150).max(150),
	expo: n.min(0).max(1),
	rate: n.min(0).max(1.5)
}).refine((c) => c.min < c.center && c.center < c.max, "Endpoints must be ordered");
var inputsSchema = z.object({
	rudder: n.min(-1).max(1),
	elevator: n.min(-1).max(1),
	leftAileron: n.min(-1).max(1),
	rightAileron: n.min(-1).max(1),
	throttle: n.min(0).max(1),
	aux1: n.min(-1).max(1),
	aux2: n.min(-1).max(1)
});
var channelSet = z.object({
	rudder: channelSchema,
	elevator: channelSchema,
	leftAileron: channelSchema,
	rightAileron: channelSchema,
	throttle: channelSchema,
	aux1: channelSchema,
	aux2: channelSchema
});
var battery = z.object({
	cells: n.int().min(1).max(12),
	chemistry: z.enum([
		"LiPo",
		"Li-ion",
		"Other"
	]),
	warning: n.min(1).max(60),
	critical: n.min(1).max(60),
	scale: n.min(.1).max(5)
}).refine((v) => v.critical < v.warning, "Critical must be below warning");
var settingsSchema = z.object({
	modes: modeSchema.optional(),
	name: z.string().min(1).max(60),
	id,
	units: z.enum(["g", "ms2"]),
	mounting: z.string().max(80),
	sampleHz: z.union([z.literal(5), z.literal(10)]),
	aircraftBattery: battery,
	transmitterBattery: battery,
	mixer: z.object({
		enabled: z.boolean(),
		common: z.boolean(),
		strength: n.min(0).max(1.5),
		differential: n.min(0).max(.8),
		version: n.int().min(1),
		channels: channelSet
	}),
	preflight: z.record(z.boolean()),
	calibration: z.array(z.object({
		at: z.string().datetime(),
		note: z.string().max(250)
	})).max(30),
	browserAudio: z.boolean()
});
var vector = z.object({
	x: nullable,
	y: nullable,
	z: nullable
}), output = z.object({
	normalized: n.min(-1).max(1),
	pwm: n.int().min(500).max(2500),
	saturated: z.boolean()
});
var frameSchema = z.object({
	safety: safetySchema.nullable().optional(),
	schemaVersion: z.literal(1),
	source: z.enum([
		"DEMO",
		"LIVE",
		"REPLAY"
	]),
	deviceId: id,
	bootId: id,
	seq: n.int().nonnegative(),
	uptimeMs: n.nonnegative(),
	receivedAt: n.nonnegative(),
	attitude: z.object({
		pitch: n.min(-180).max(180).nullable(),
		roll: n.min(-180).max(180).nullable(),
		yaw: nullable
	}),
	accel: vector,
	gyro: vector,
	linearAcceleration: vector.nullable(),
	chipTemp: n.min(-80).max(150).nullable(),
	sampleHz: n.min(0).max(8e3).nullable(),
	aircraftVoltage: n.min(0).max(65).nullable(),
	transmitterVoltage: n.min(0).max(65).nullable(),
	radio: z.object({
		received: n.int().nonnegative(),
		expected: n.int().positive(),
		retries: n.int().nonnegative(),
		packetAge: n.nonnegative(),
		rpd: bool
	}).refine((r) => r.received <= r.expected, "Invalid packet counters").nullable(),
	links: z.object({
		radio: bool,
		uart: bool,
		wifi: bool,
		uplink: bool
	}),
	wifiRssi: n.min(-130).max(0).nullable(),
	imu: bool,
	armed: bool,
	mode: z.string().max(80).nullable(),
	inputs: inputsSchema.nullable(),
	outputs: z.object({
		rudder: output.optional(),
		elevator: output.optional(),
		leftAileron: output.optional(),
		rightAileron: output.optional(),
		throttle: output.optional(),
		aux1: output.optional(),
		aux2: output.optional()
	}),
	mixEnabled: bool,
	configVersion: n.int().nonnegative().nullable(),
	validity: z.record(z.enum([
		"valid",
		"invalid",
		"unsupported",
		"not_installed",
		"unknown"
	]))
});
var servoAuditSchema = z.object({
	id: z.string().uuid(),
	aircraftId: id,
	issuer: z.string().min(1).max(150),
	environment: z.literal("DEMO"),
	kind: z.literal("servo.test"),
	parameters: z.object({
		axis: z.enum([
			"leftAileron",
			"rightAileron",
			"elevator",
			"rudder"
		]),
		value: n.min(-1).max(1)
	}),
	createdAt: n.nonnegative(),
	expiresAt: n.nonnegative(),
	status: z.enum(["Applied (simulator)", "Rejected"]),
	reason: z.string().max(500),
	sent: z.literal(false)
});
var demoAuditSchema = z.union([servoAuditSchema, servoAuditSchema.extend({
	kind: z.literal("parachute.deploy"),
	parameters: z.object({ guardConfirmed: z.literal(true) })
})]);
var eventSchema = z.object({
	environment: z.enum([
		"DEMO",
		"LIVE",
		"REPLAY"
	]).optional(),
	aircraftId: id.optional(),
	configuration: settingsSchema.optional(),
	command: demoAuditSchema.optional(),
	id: z.string().max(100),
	at: n.nonnegative(),
	title: z.string().max(120),
	detail: z.string().max(1200),
	source: z.string().max(60),
	severity: z.enum([
		"info",
		"warning",
		"critical"
	]),
	acknowledged: z.boolean(),
	resolved: z.boolean()
});
var recordingSchema = z.object({
	id: z.string().uuid(),
	name: z.string().min(1).max(120),
	notes: z.string().max(4e3),
	createdAt: n.nonnegative(),
	source: z.enum(["DEMO", "LIVE"]),
	frames: z.array(frameSchema).max(18e3),
	events: z.array(eventSchema).max(250),
	settings: settingsSchema
}).refine((r) => r.frames.every((f, i) => f.source === r.source && (!i || f.receivedAt >= r.frames[i - 1].receivedAt)), "Source mismatch or out-of-order frames");
z.object({
	schemaVersion: z.literal(1),
	deviceId: id,
	bootId: id,
	firmware: z.object({
		nano: z.string().max(60),
		node: z.string().max(60)
	}),
	features: z.record(z.boolean()),
	commands: z.array(z.enum([
		"servo.test",
		"mixer.configure",
		"imu.calibrate",
		"aux.move",
		"motor.test",
		"parachute.deploy"
	])).max(6),
	maintenance: z.object({
		authorized: z.boolean(),
		expiresAt: n.nonnegative()
	}),
	units: z.object({
		acceleration: z.literal("m/s2"),
		angularVelocity: z.literal("deg/s"),
		attitude: z.literal("deg"),
		voltage: z.literal("V"),
		pwm: z.literal("us")
	})
});
var commandSchema = z.object({
	schemaVersion: z.literal(1),
	id: z.string().uuid(),
	aircraftId: id,
	environment: z.enum([
		"LIVE",
		"DEMO",
		"REPLAY"
	]),
	kind: z.enum([
		"servo.test",
		"mixer.configure",
		"imu.calibrate",
		"aux.move",
		"motor.test",
		"parachute.deploy"
	]),
	parameters: z.record(z.union([
		z.string().max(100),
		n,
		z.boolean(),
		z.null()
	])),
	expiresAt: n.nonnegative()
});
z.object({
	schemaVersion: z.literal(1),
	commandId: z.string().uuid(),
	deviceId: id,
	bootId: id,
	sequence: n.int().nonnegative(),
	uptimeMs: n.nonnegative(),
	status: z.enum([
		"Accepted",
		"Applied",
		"Rejected",
		"TimedOut"
	]),
	reason: z.string().max(500).nullable()
});
//#endregion
//#region supabase/functions/flight-api/index.ts
var service = createClient(Deno.env.get("SUPABASE_URL"), Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"), { auth: {
	persistSession: false,
	autoRefreshToken: false
} });
var allowed = (Deno.env.get("ALLOWED_ORIGINS") ?? "").split(",").map((x) => x.trim());
function checked(r) {
	if (r.error) throw Error("Database operation failed");
	return r.data;
}
Deno.serve(async (req) => {
	const origin = req.headers.get("origin") ?? "", cors = {
		"Access-Control-Allow-Origin": allowed.includes(origin) ? origin : "null",
		"Vary": "Origin",
		"Access-Control-Allow-Headers": "authorization,apikey,content-type,x-client-info",
		"Access-Control-Allow-Methods": "POST,OPTIONS"
	};
	const result = (data, status = 200) => Response.json({
		status,
		data
	}, { headers: cors });
	const fail = (error, status) => Response.json({ error }, {
		status,
		headers: cors
	});
	if (req.method === "OPTIONS") return new Response(null, {
		status: 204,
		headers: cors
	});
	if (req.method !== "POST" || !allowed.includes(origin)) return fail("Origin or method not allowed", 403);
	try {
		const token = req.headers.get("authorization")?.replace(/^Bearer /i, "");
		if (!token) return fail("Sign in required", 401);
		const { data: { user }, error } = await service.auth.getUser(token);
		if (error || !user?.email_confirmed_at) return fail("Verified email required", 401);
		const raw = await req.text();
		if (raw.length > 25e6) return fail("Request too large", 413);
		const input = z.object({
			resource: z.string(),
			method: z.enum([
				"GET",
				"POST",
				"PUT"
			]),
			workspace: z.string().uuid().optional(),
			query: z.record(z.string()).default({}),
			body: z.unknown().nullable()
		}).parse(JSON.parse(raw));
		const w = input.workspace ?? user.id, { resource, method, query } = input;
		const member = checked(await service.from("fd_members").select("role").eq("workspace_id", w).eq("user_id", user.id).maybeSingle());
		if (!member) return fail("No access to this workspace", 403);
		if (method !== "GET" && !["owner", "operator"].includes(member.role)) return fail("Viewer access is read-only", 403);
		const rows = async (kind) => checked(await service.from("fd_records").select("id,payload").eq("workspace_id", w).eq("kind", kind).order("updated_at", { ascending: false }).limit(250));
		const get = async (kind, id) => checked(await service.from("fd_records").select("payload").eq("workspace_id", w).eq("kind", kind).eq("id", id).maybeSingle())?.payload;
		const put = async (kind, id, payload) => checked(await service.from("fd_records").upsert({
			workspace_id: w,
			kind,
			id,
			payload,
			updated_at: (/* @__PURE__ */ new Date()).toISOString()
		}, { onConflict: "workspace_id,kind,id" }));
		if (resource === "workspace" && method === "GET") return result({
			account: {
				authenticated: true,
				user: {
					userId: user.id,
					displayName: user.email
				},
				role: member.role,
				workspace: w
			},
			settings: await get("settings", "current") ?? null,
			recordings: (await rows("recordings")).map((r) => ({
				...r.payload,
				frames: [],
				events: [],
				saved: true
			}))
		});
		if (resource === "workspace" && method === "PUT") {
			await put("settings", "current", z.object({ settings: settingsSchema }).parse(input.body).settings);
			return result({ saved: true });
		}
		if (resource === "profiles" && method === "GET") return result((await rows("profiles")).map((r) => r.payload));
		if (resource === "profiles" && method === "POST") {
			const d = z.object({
				id: z.string().uuid(),
				name: z.string().min(1).max(80),
				settings: settingsSchema
			}).parse(input.body);
			await put("profiles", d.id, d);
			return result({ saved: true });
		}
		if (resource === "recordings" && method === "POST") {
			const d = recordingSchema.parse(input.body), key = `${w}/${d.id}.json`;
			checked(await service.storage.from("flight-recordings").upload(key, JSON.stringify(d), {
				contentType: "application/json",
				upsert: true
			}));
			const { frames, events, ...metadata } = d;
			await put("recordings", d.id, {
				...metadata,
				sampleCount: frames.length,
				objectKey: key
			});
			return result({ saved: true });
		}
		if (resource === "recordings" && method === "GET") {
			const metadata = await get("recordings", z.string().uuid().parse(query.id));
			if (!metadata) return fail("Recording not found", 404);
			const blob = checked(await service.storage.from("flight-recordings").download(metadata.objectKey));
			return result(JSON.parse(await blob.text()));
		}
		if (resource === "alerts" && method === "GET") return result((await rows("alerts")).map((r) => r.payload));
		if (resource === "alerts" && method === "POST") {
			const events = query.batch === "1" ? z.object({ events: z.array(eventSchema).min(1).max(250) }).parse(input.body).events : [eventSchema.parse(input.body)];
			if (new Set(events.map((e) => e.id)).size !== events.length) return fail("Duplicate event IDs", 400);
			checked(await service.from("fd_records").upsert(events.map((e) => ({
				workspace_id: w,
				kind: "alerts",
				id: e.id,
				payload: e,
				updated_at: (/* @__PURE__ */ new Date()).toISOString()
			})), { onConflict: "workspace_id,kind,id" }));
			return result({ saved: true });
		}
		if (resource === "telemetry" && method === "GET") {
			const id = z.string().min(1).max(80).parse(query.aircraftId);
			const row = checked(await service.from("fd_telemetry").select("frame,capabilities").eq("workspace_id", w).eq("device_id", id).maybeSingle());
			return result({
				frame: row?.frame ?? null,
				capabilities: row?.capabilities ?? null,
				hardwareCommandsEnabled: false
			});
		}
		if (resource === "members" && method === "POST") {
			if (member.role !== "owner") return fail("Owner required", 403);
			const d = z.object({
				userId: z.string().uuid(),
				role: z.enum(["operator", "viewer"])
			}).parse(input.body);
			if (d.userId === w) return fail("Cannot change owner role", 400);
			const { data: { user: target } } = await service.auth.admin.getUserById(d.userId);
			if (!target?.email_confirmed_at) return fail("Member must verify their email first", 404);
			checked(await service.from("fd_members").upsert({
				workspace_id: w,
				user_id: d.userId,
				role: d.role
			}));
			return result({
				saved: true,
				workspace: w
			});
		}
		if (resource === "commands" && method === "GET") return result((await rows("commands")).map((r) => r.payload));
		if (resource === "commands" && method === "POST") {
			const c = commandSchema.parse(input.body), reason = "Live actuator transport is disabled. Device enforcement is not validated.", audit = {
				...c,
				issuer: user.id,
				status: "Rejected",
				reason,
				sent: false,
				createdAt: Date.now()
			};
			const { error } = await service.from("fd_records").insert({
				workspace_id: w,
				kind: "commands",
				id: c.id,
				payload: audit
			});
			if (error) return fail("Duplicate or unavailable command audit; never sent", 409);
			return result({
				id: c.id,
				status: "Rejected",
				reason,
				sent: false
			}, 422);
		}
		return fail("Endpoint not found", 404);
	} catch (e) {
		return fail(e instanceof z.ZodError ? "Invalid request data" : "Service unavailable. Unsaved work remains in this tab.", 400);
	}
});
//#endregion
export {};
