// @ts-nocheck
// Generated by pnpm functions:bundle. Edit the canonical source, then regenerate.
// Function name: telemetry-ingest
// Source SHA-256: 0dde30288f93e0380919a6e2f3406442a2bf638f154f8eb344abee79b3ce0eeb
// Uses server-side authentication. Deploy with verify_jwt=false as documented.
import { createClient } from "npm:@supabase/supabase-js@2.116.0";
import { z } from "npm:zod@3.25.76";
//#region supabase/functions/_shared/safety.ts
/** Additive v1 telemetry extension. Missing fields never mean healthy. */
var safetySchema = z.object({
	schemaVersion: z.literal(1),
	flightFailure: z.boolean().nullable(),
	failureReason: z.string().max(250).nullable(),
	readyForTakeoff: z.boolean().nullable(),
	parachute: z.object({
		installed: z.boolean().nullable(),
		ready: z.boolean().nullable(),
		state: z.enum([
			"unknown",
			"stowed",
			"released",
			"deployed",
			"fault"
		]),
		feedback: z.enum([
			"none",
			"release_sensor",
			"deployment_sensor"
		])
	}).nullable()
});
function sanitizeSafety(f, c) {
	if (!f.safety || !c || c.deviceId !== f.deviceId || c.bootId !== f.bootId || f.validity.safety !== "valid" || f.links.uart !== true || [
		"invalid",
		"unknown",
		"unsupported",
		"not_installed"
	].includes(f.validity.uart)) return null;
	const report = structuredClone(f.safety);
	if (!c.features.flightFailureDetection) {
		report.flightFailure = null;
		report.failureReason = null;
	}
	if (!c.features.takeoffReadiness) report.readyForTakeoff = null;
	if (!c.features.parachute) report.parachute = null;
	const p = report.parachute;
	if (p) {
		if (p.installed !== true) {
			p.ready = null;
			p.state = "unknown";
			p.feedback = "none";
		}
		if (!c.features.parachuteFeedback) p.feedback = "none";
		if (p.state === "deployed" && p.feedback !== "deployment_sensor") p.state = "unknown";
	}
	return report;
}
//#endregion
//#region supabase/functions/_shared/modes.ts
var neutral = {
	leftAileron: 0,
	rightAileron: 0,
	elevator: 0,
	rudder: 0
};
var finite = z.number().finite();
var anglesSchema = z.object({
	leftAileron: finite.min(-45).max(45),
	rightAileron: finite.min(-45).max(45),
	elevator: finite.min(-45).max(45),
	rudder: finite.min(-45).max(45)
});
var preset = z.object({
	angles: anglesSchema,
	transitionSeconds: finite.min(1).max(15)
});
var modeSchema = z.object({
	version: z.number().int().positive(),
	presets: z.object({
		cruise: preset,
		takeoff: preset,
		landing: preset
	}),
	travelDegrees: z.object({
		leftAileron: finite.min(1).max(45),
		rightAileron: finite.min(1).max(45),
		elevator: finite.min(1).max(45),
		rudder: finite.min(1).max(45)
	}),
	maxDegreesPerSecond: finite.min(1).max(30),
	startup: z.object({
		enabled: z.boolean(),
		delaySeconds: z.literal(5),
		amplitudeDegrees: finite.min(1).max(10)
	})
});
({ ...neutral }), { ...neutral }, { ...neutral };
//#endregion
//#region supabase/functions/_shared/contracts.ts
var n = z.number().finite(), nullable = n.nullable(), id = z.string().min(1).max(80).regex(/^[A-Za-z0-9_-]+$/), bool = z.boolean().nullable();
var channelSchema = z.object({
	name: z.string().min(1).max(60),
	min: n.min(750).max(2250),
	center: n.min(750).max(2250),
	max: n.min(750).max(2250),
	reverse: z.boolean(),
	deadband: n.min(0).max(.2),
	trim: n.min(-.3).max(.3),
	subtrim: n.min(-150).max(150),
	expo: n.min(0).max(1),
	rate: n.min(0).max(1.5)
}).refine((c) => c.min < c.center && c.center < c.max, "Endpoints must be ordered");
var inputsSchema = z.object({
	rudder: n.min(-1).max(1),
	elevator: n.min(-1).max(1),
	leftAileron: n.min(-1).max(1),
	rightAileron: n.min(-1).max(1),
	throttle: n.min(0).max(1),
	aux1: n.min(-1).max(1),
	aux2: n.min(-1).max(1)
});
var channelSet = z.object({
	rudder: channelSchema,
	elevator: channelSchema,
	leftAileron: channelSchema,
	rightAileron: channelSchema,
	throttle: channelSchema,
	aux1: channelSchema,
	aux2: channelSchema
});
var battery = z.object({
	cells: n.int().min(1).max(12),
	chemistry: z.enum([
		"LiPo",
		"Li-ion",
		"Other"
	]),
	warning: n.min(1).max(60),
	critical: n.min(1).max(60),
	scale: n.min(.1).max(5)
}).refine((v) => v.critical < v.warning, "Critical must be below warning");
var settingsSchema = z.object({
	modes: modeSchema.optional(),
	name: z.string().min(1).max(60),
	id,
	units: z.enum(["g", "ms2"]),
	mounting: z.string().max(80),
	sampleHz: z.union([z.literal(5), z.literal(10)]),
	aircraftBattery: battery,
	transmitterBattery: battery,
	mixer: z.object({
		enabled: z.boolean(),
		common: z.boolean(),
		strength: n.min(0).max(1.5),
		differential: n.min(0).max(.8),
		version: n.int().min(1),
		channels: channelSet
	}),
	preflight: z.record(z.boolean()),
	calibration: z.array(z.object({
		at: z.string().datetime(),
		note: z.string().max(250)
	})).max(30),
	browserAudio: z.boolean()
});
var vector = z.object({
	x: nullable,
	y: nullable,
	z: nullable
}), output = z.object({
	normalized: n.min(-1).max(1),
	pwm: n.int().min(500).max(2500),
	saturated: z.boolean()
});
var frameSchema = z.object({
	safety: safetySchema.nullable().optional(),
	schemaVersion: z.literal(1),
	source: z.enum([
		"DEMO",
		"LIVE",
		"REPLAY"
	]),
	deviceId: id,
	bootId: id,
	seq: n.int().nonnegative(),
	uptimeMs: n.nonnegative(),
	receivedAt: n.nonnegative(),
	attitude: z.object({
		pitch: n.min(-180).max(180).nullable(),
		roll: n.min(-180).max(180).nullable(),
		yaw: nullable
	}),
	accel: vector,
	gyro: vector,
	linearAcceleration: vector.nullable(),
	chipTemp: n.min(-80).max(150).nullable(),
	sampleHz: n.min(0).max(8e3).nullable(),
	aircraftVoltage: n.min(0).max(65).nullable(),
	transmitterVoltage: n.min(0).max(65).nullable(),
	radio: z.object({
		received: n.int().nonnegative(),
		expected: n.int().positive(),
		retries: n.int().nonnegative(),
		packetAge: n.nonnegative(),
		rpd: bool
	}).refine((r) => r.received <= r.expected, "Invalid packet counters").nullable(),
	links: z.object({
		radio: bool,
		uart: bool,
		wifi: bool,
		uplink: bool
	}),
	wifiRssi: n.min(-130).max(0).nullable(),
	imu: bool,
	armed: bool,
	mode: z.string().max(80).nullable(),
	inputs: inputsSchema.nullable(),
	outputs: z.object({
		rudder: output.optional(),
		elevator: output.optional(),
		leftAileron: output.optional(),
		rightAileron: output.optional(),
		throttle: output.optional(),
		aux1: output.optional(),
		aux2: output.optional()
	}),
	mixEnabled: bool,
	configVersion: n.int().nonnegative().nullable(),
	validity: z.record(z.enum([
		"valid",
		"invalid",
		"unsupported",
		"not_installed",
		"unknown"
	]))
});
var servoAuditSchema = z.object({
	id: z.string().uuid(),
	aircraftId: id,
	issuer: z.string().min(1).max(150),
	environment: z.literal("DEMO"),
	kind: z.literal("servo.test"),
	parameters: z.object({
		axis: z.enum([
			"leftAileron",
			"rightAileron",
			"elevator",
			"rudder"
		]),
		value: n.min(-1).max(1)
	}),
	createdAt: n.nonnegative(),
	expiresAt: n.nonnegative(),
	status: z.enum(["Applied (simulator)", "Rejected"]),
	reason: z.string().max(500),
	sent: z.literal(false)
});
var demoAuditSchema = z.union([servoAuditSchema, servoAuditSchema.extend({
	kind: z.literal("parachute.deploy"),
	parameters: z.object({ guardConfirmed: z.literal(true) })
})]);
var eventSchema = z.object({
	environment: z.enum([
		"DEMO",
		"LIVE",
		"REPLAY"
	]).optional(),
	aircraftId: id.optional(),
	configuration: settingsSchema.optional(),
	command: demoAuditSchema.optional(),
	id: z.string().max(100),
	at: n.nonnegative(),
	title: z.string().max(120),
	detail: z.string().max(1200),
	source: z.string().max(60),
	severity: z.enum([
		"info",
		"warning",
		"critical"
	]),
	acknowledged: z.boolean(),
	resolved: z.boolean()
});
z.object({
	id: z.string().uuid(),
	name: z.string().min(1).max(120),
	notes: z.string().max(4e3),
	createdAt: n.nonnegative(),
	source: z.enum(["DEMO", "LIVE"]),
	frames: z.array(frameSchema).max(18e3),
	events: z.array(eventSchema).max(250),
	settings: settingsSchema
}).refine((r) => r.frames.every((f, i) => f.source === r.source && (!i || f.receivedAt >= r.frames[i - 1].receivedAt)), "Source mismatch or out-of-order frames");
var capabilitiesSchema = z.object({
	schemaVersion: z.literal(1),
	deviceId: id,
	bootId: id,
	firmware: z.object({
		nano: z.string().max(60),
		node: z.string().max(60)
	}),
	features: z.record(z.boolean()),
	commands: z.array(z.enum([
		"servo.test",
		"mixer.configure",
		"imu.calibrate",
		"aux.move",
		"motor.test",
		"parachute.deploy"
	])).max(6),
	maintenance: z.object({
		authorized: z.boolean(),
		expiresAt: n.nonnegative()
	}),
	units: z.object({
		acceleration: z.literal("m/s2"),
		angularVelocity: z.literal("deg/s"),
		attitude: z.literal("deg"),
		voltage: z.literal("V"),
		pwm: z.literal("us")
	})
});
z.object({
	schemaVersion: z.literal(1),
	id: z.string().uuid(),
	aircraftId: id,
	environment: z.enum([
		"LIVE",
		"DEMO",
		"REPLAY"
	]),
	kind: z.enum([
		"servo.test",
		"mixer.configure",
		"imu.calibrate",
		"aux.move",
		"motor.test",
		"parachute.deploy"
	]),
	parameters: z.record(z.union([
		z.string().max(100),
		n,
		z.boolean(),
		z.null()
	])),
	expiresAt: n.nonnegative()
});
z.object({
	schemaVersion: z.literal(1),
	commandId: z.string().uuid(),
	deviceId: id,
	bootId: id,
	sequence: n.int().nonnegative(),
	uptimeMs: n.nonnegative(),
	status: z.enum([
		"Accepted",
		"Applied",
		"Rejected",
		"TimedOut"
	]),
	reason: z.string().max(500).nullable()
});
function sanitizeTelemetry(frame, caps) {
	const f = structuredClone(frame), missing = () => ({
		x: null,
		y: null,
		z: null
	});
	const invalid = (key) => [
		"invalid",
		"unsupported",
		"not_installed",
		"unknown"
	].includes(f.validity[key]);
	if (f.imu !== true || invalid("imu")) {
		f.attitude = {
			pitch: null,
			roll: null,
			yaw: null
		};
		f.accel = missing();
		f.gyro = missing();
		f.linearAcceleration = null;
		f.chipTemp = null;
		f.sampleHz = null;
	}
	if (invalid("accel")) f.accel = missing();
	if (invalid("gyro")) f.gyro = missing();
	if (!caps.features.attitude || invalid("attitude")) f.attitude = {
		pitch: null,
		roll: null,
		yaw: null
	};
	if (!caps.features.relativeYaw) f.attitude.yaw = null;
	if (!caps.features.linearAcceleration || invalid("linearAcceleration")) f.linearAcceleration = null;
	if (invalid("battery") || invalid("aircraftBattery")) f.aircraftVoltage = null;
	if (invalid("transmitterBattery")) f.transmitterVoltage = null;
	if (f.links.uart === false || invalid("uart")) {
		f.inputs = null;
		f.outputs = {};
		f.radio = null;
		f.transmitterVoltage = null;
		f.armed = null;
		f.mode = null;
		f.mixEnabled = null;
		f.configVersion = null;
		f.links.radio = null;
	}
	f.safety = sanitizeSafety(f, caps);
	return f;
}
//#endregion
//#region supabase/functions/telemetry-ingest/index.ts
var db = createClient(Deno.env.get("SUPABASE_URL"), Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"), { auth: { persistSession: false } });
async function equal(a, b) {
	const e = new TextEncoder(), [x, y] = await Promise.all([a, b].map((s) => crypto.subtle.digest("SHA-256", e.encode(s))));
	let d = 0;
	const p = new Uint8Array(x), q = new Uint8Array(y);
	for (let i = 0; i < p.length; i++) d |= p[i] ^ q[i];
	return d === 0;
}
Deno.serve(async (req) => {
	if (req.method !== "POST") return new Response("POST only", { status: 405 });
	const expected = Deno.env.get("DEVICE_SHARED_TOKEN") ?? "";
	if (expected.length < 32 || !await equal(req.headers.get("x-device-token") ?? "", expected)) return new Response("Unauthorized", { status: 401 });
	try {
		const raw = await req.text();
		if (raw.length > 16384) return new Response("Payload too large", { status: 413 });
		const payload = JSON.parse(raw), f = frameSchema.parse(payload.frame), c = capabilitiesSchema.parse(payload.capabilities);
		if (f.source !== "LIVE" || f.deviceId !== Deno.env.get("DEVICE_ID") || c.deviceId !== f.deviceId || c.bootId !== f.bootId) return new Response("Invalid device or source", { status: 400 });
		f.receivedAt = Date.now();
		const clean = sanitizeTelemetry(f, c);
		const { data, error } = await db.rpc("fd_ingest", {
			w: Deno.env.get("DEVICE_WORKSPACE_ID"),
			d: f.deviceId,
			b: f.bootId,
			s: f.seq,
			t: f.receivedAt,
			f: clean,
			c
		});
		if (error) return new Response("Ingestion unavailable", { status: 503 });
		return Response.json({
			accepted: data,
			serverReceiveTime: f.receivedAt
		}, { status: data ? 200 : 409 });
	} catch {
		return new Response("Invalid telemetry", { status: 400 });
	}
});
//#endregion
export {};
