import {ReactNode,useEffect,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {Plane,Mail,ArrowRight,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {InputOTP,InputOTPGroup,InputOTPSlot} from '@/components/ui/input-otp';
import {supabase} from '@/lib/supabase';
export function AuthGate({children}:{children:ReactNode}){
 const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[demo,setDemo]=useState(false),[email,setEmail]=useState(''),[code,setCode]=useState(''),[stage,setStage]=useState<'email'|'code'>('email'),[create,setCreate]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[cooldown,setCooldown]=useState(0);
 useEffect(()=>{if(!supabase){setLoading(false);return}let active=true;supabase.auth.getSession().then(({data,error})=>{if(active){setSession(data.session);setLoading(false);if(error)setError(error.message)}});const {data}=supabase.auth.onAuthStateChange((_event,s)=>{setSession(s);if(s)setDemo(false)});return()=>{active=false;data.subscription.unsubscribe()}},[]);
 useEffect(()=>{if(!cooldown)return;const timer=setTimeout(()=>setCooldown(c=>Math.max(0,c-1)),1000);return()=>clearTimeout(timer)},[cooldown]);
 async function send(){if(!supabase||busy||cooldown)return;setBusy(true);setError('');try{const {error}=await supabase.auth.signInWithOtp({email:email.trim(),options:{shouldCreateUser:create}});if(error)throw error;setStage('code');setCode('');setCooldown(60)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function verify(){if(!supabase||busy)return;setBusy(true);setError('');try{const {error}=await supabase.auth.verifyOtp({email:email.trim(),token:code,type:'email'});if(error)throw error;setCode('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(loading)return <div className="auth-shell"><p>Connecting your workspace…</p></div>;
 if(session||demo)return <div key={session?.user.id??'demo'}><div className="account-strip"><span>{session?'Verified account · '+session.user.email:'Guest simulator · no account required'}</span><Button size="sm" variant="ghost" onClick={async()=>{if(session&&supabase){const {error}=await supabase.auth.signOut();if(error){setError(error.message);return}}setDemo(false)}}>{session?'Sign out':'Sign in / Create account'}</Button></div>{error&&<p role="alert">{error}</p>}{children}</div>;
 return <div className="auth-shell"><section className="auth-story"><div className="brand"><Plane/>FLIGHT DECK</div><span className="eyebrow">FIXED-WING OPERATIONS</span><h1>Clarity on every<br/><em>control surface.</em></h1><p>One workspace for aircraft telemetry, radio diagnostics, and deliberate preflight checks.</p><div className="auth-orbit"><Plane size={110}/><span>LOCAL CONTROL FIRST</span></div><p className="copy"><ShieldCheck size={16}/> Physical radio control and aircraft failsafes stay onboard.</p></section><section className="auth-card"><Mail className="good" size={30}/><h2>{stage==='code'?'Check your inbox':create?'Create your workspace':'Welcome back'}</h2><p className="copy">{stage==='code'?`Enter the verification code sent to ${email}.`:'Use your email to receive a one-time verification code.'}</p>{!supabase&&<div className="notice">Email login is awaiting Supabase configuration. The demo is available below. <a href="./SETUP.md">Setup guide ↗</a></div>}<form onSubmit={e=>{e.preventDefault();void(stage==='code'?verify():send())}} className="stack">{stage==='email'?<label className="field">Email address<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" disabled={busy}/></label>:<><InputOTP aria-label="Email verification code" maxLength={6} value={code} onChange={setCode} pattern="[0-9]*" inputMode="numeric" autoComplete="one-time-code"><InputOTPGroup>{Array.from({length:6},(_,index)=><InputOTPSlot key={index} index={index}/>)}</InputOTPGroup></InputOTP><p className="copy">Codes are single use. Expiration is enforced by the authentication server.</p></>}{error&&<p role="alert" className="warning">{error}</p>}<Button disabled={!supabase||busy||(stage==='code'&&code.length!==6)} type="submit">{busy?'Please wait…':stage==='code'?'Verify & enter workspace':create?'Create account & send code':'Send verification code'}<ArrowRight size={16}/></Button></form>{stage==='code'?<div className="button-row"><Button variant="ghost" disabled={busy||cooldown>0} onClick={()=>void send()}>{cooldown?`Resend in ${cooldown}s`:'Resend code'}</Button><Button variant="ghost" onClick={()=>{setStage('email');setCode('');setError('')}}>Change email</Button></div>:<Button variant="ghost" onClick={()=>{setCreate(!create);setError('')}}>{create?'Already registered? Sign in':'New here? Create an account'}</Button>}<div className="auth-divider"/><Button variant="outline" onClick={()=>setDemo(true)}>Explore the interactive demo</Button><p className="copy">Demo data is simulated. Access to saved aircraft data requires a verified account.</p></section></div>;
}
