'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Choice,apiJson,postOptions,download,Pill} from './controls';
import {FlightEvent} from '@/lib/flight';
import {Account} from './flight-deck';
import {toast} from 'sonner';
export function EventHistory({events,account}:{events:FlightEvent[];account:Account}) {
 const [open,setOpen]=useState(false),[saved,setSaved]=useState<FlightEvent[]>([]),[view,setView]=useState('current'),[severity,setSeverity]=useState('all'),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const rows=(view==='saved'?saved:events).filter(e=>(severity==='all'||e.severity===severity)&&`${e.title} ${e.detail} ${e.source} ${e.aircraftId??''}`.toLowerCase().includes(search.toLowerCase()));
 const load=async()=>{setBusy(true);setError('');try{setSaved(await apiJson<FlightEvent[]>('/api/alerts'));setView('saved')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const save=async()=>{setBusy(true);setError('');try{await apiJson('/api/alerts?batch=1',postOptions({events}));toast.success('Event history saved')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <><Button variant="outline" size="sm" onClick={()=>setOpen(true)}>Event history</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent style={{maxWidth:820,maxHeight:'85dvh',overflow:'auto'}}><DialogHeader><DialogTitle>Event history</DialogTitle><DialogDescription>Archived events describe past observations, not the aircraft’s current condition. Acknowledgment does not resolve a fault.</DialogDescription></DialogHeader><div className="button-row"><Button variant="outline" onClick={()=>setView('current')}>Current environment</Button><Button variant="outline" disabled={!account.authenticated||busy} onClick={()=>void load()}>Load saved history</Button><Button disabled={!account.authenticated||account.role==='viewer'||busy||!events.length} onClick={()=>void save()}>Save current history</Button><Button variant="outline" onClick={()=>download('flight-deck-events.json',JSON.stringify(rows,null,2))}>Export filtered JSON</Button></div><p className="copy">{view==='saved'?'Latest 250 saved events across this workspace.':'Up to 250 events from this environment. Save or export before switching environments.'} {!account.authenticated&&'Sign in to save history; guest exports work without credentials.'}</p>{error&&<p role="alert" className="warning">{error}</p>}<input aria-label="Search events" placeholder="Search events, sources or aircraft…" value={search} onChange={e=>setSearch(e.target.value)}/><Choice label="Event severity" value={severity} onChange={setSeverity} options={['all','info','warning','critical'].map(value=>({value,label:value}))}/>{rows.map(e=><article className="event" key={e.id}><div className="status-line"><strong>{e.title}</strong><Pill>{e.environment??'Unknown environment'}</Pill></div><p>{e.detail}</p><small>{new Date(e.at).toISOString()} · {e.source} · {e.aircraftId??'Unknown aircraft'} · {e.severity}</small><p>{e.acknowledged?'Acknowledged':'Not acknowledged'} · {e.resolved?'Resolved at last observation':'Not recorded as resolved'}</p>{e.configuration&&<details><summary>Requested configuration snapshot</summary><pre style={{overflow:'auto',maxHeight:240}}>{JSON.stringify(e.configuration,null,2)}</pre></details>}{e.command&&<details><summary>Command audit record</summary><pre style={{overflow:'auto',maxHeight:240}}>{JSON.stringify(e.command,null,2)}</pre></details>}</article>)}{!rows.length&&<p className="copy">No matching events.</p>}</DialogContent></Dialog></>;
}
