'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {toast} from 'sonner';
import {Axis,axes,Inputs,Channel,zeroInputs,latchMix,auxiliaryCommand,fmt} from '@/lib/flight';
import {Panel,SurfaceView} from './instruments';
import {Choice,NumberField,Pill,Range} from './controls';
import type {WorkspaceProps} from './flight-deck';
const assignment:Record<Axis,{input:string;pin:string;out:string;name:string}>={rudder:{input:'Joystick 1 X',pin:'A0',out:'D5',name:'Rudder'},elevator:{input:'Joystick 1 Y',pin:'A1',out:'D4',name:'Elevator'},leftAileron:{input:'Joystick 2 X',pin:'A2',out:'D2',name:'Left aileron / roll'},rightAileron:{input:'Joystick 2 Y',pin:'A3',out:'D3',name:'Right aileron / optional common'},throttle:{input:'Slider',pin:'A6',out:'D6',name:'Throttle'},aux1:{input:'Potentiometer 1',pin:'A4',out:'Not mapped',name:'Auxiliary / trim'},aux2:{input:'Potentiometer 2',pin:'A5',out:'Not mapped',name:'Auxiliary / trim'}};
function Joystick({x,y,label,onMove}:{x:number|null;y:number|null;label:string;onMove?:(x:number,y:number)=>void}){const move=(e:React.PointerEvent<HTMLDivElement>)=>{if(!onMove||!e.buttons)return;const r=e.currentTarget.getBoundingClientRect();onMove(Math.max(-1,Math.min(1,(e.clientX-r.left-r.width/2)/(r.width*.4))),Math.max(-1,Math.min(1,-(e.clientY-r.top-r.height/2)/(r.height*.4))))};return <div><div className="eyebrow text-center">{label}</div><div className="joystick" aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);move(e)}} onPointerMove={move} style={{touchAction:'none'}}>{x!==null&&y!==null&&<span style={{left:`${50+x*40}%`,top:`${50-y*40}%`}}/>}</div><div className="row muted text-xs" style={{justifyContent:'space-around'}}><span>X <b className="mono">{fmt(x,2)}</b></span><span>Y <b className="mono">{fmt(y,2)}</b></span></div></div>}
export function MixerPage(p:WorkspaceProps){const {settings:s,setSettings,frame:f,environment,manual,setManual}=p,[axis,setAxis]=useState<Axis>('leftAileron'),[aux,setAux]=useState('STOP'),[buttons,setButtons]=useState([false,false,false,false]),pressed=useRef([false,false,false,false]),timeout=useRef<ReturnType<typeof setTimeout>|null>(null);const demo=environment==='DEMO',editable=environment!=='REPLAY',m=s.mixer,input=manual??f.inputs??zeroInputs,c=m.channels[axis];
 const update=(patch:Partial<typeof m>)=>setSettings(old=>({...old,mixer:{...old.mixer,...patch,version:old.mixer.version+1}}));
 const channel=(patch:Partial<Channel>)=>setSettings(old=>({...old,mixer:{...old.mixer,version:old.mixer.version+1,channels:{...old.mixer.channels,[axis]:{...old.mixer.channels[axis],...patch}}}}));
 const move=(patch:Partial<Inputs>)=>setManual({...input,...patch});
 const push=(i:number,down:boolean)=>{if(!demo)return;pressed.current[i]=down;setButtons([...pressed.current]);if(i<2&&down){const next=latchMix(m.enabled,pressed.current[0],pressed.current[1]);if(next!==m.enabled){update({enabled:next});p.addEvent(`Mixing ${next?'enabled':'disabled'}`,'Latched simulator command. Releasing the button retains the mode.','info','Controller')}}if(i>=2){setAux(auxiliaryCommand(pressed.current[2],pressed.current[3]));if(timeout.current)clearTimeout(timeout.current);if(down)timeout.current=setTimeout(()=>{pressed.current[2]=false;pressed.current[3]=false;setButtons([...pressed.current]);setAux('STOP')},500)}};
 useEffect(()=>{const stop=()=>{pressed.current=[false,false,false,false];setButtons([...pressed.current]);setAux('STOP')};window.addEventListener('blur',stop);return()=>{window.removeEventListener('blur',stop);if(timeout.current)clearTimeout(timeout.current)}},[]);
 return <div className="stack"><div className="status-line"><span>{m.enabled?'Roll mixing':'Independent / test configuration'}</span><span className="row"><Pill tone={m.enabled?'good':'warning'}>MIX {m.enabled?'ON':'OFF'}</Pill>Requested v{m.version} / {demo?'Simulator':'Aircraft'} confirmed {f.configVersion??'Unknown'}</span></div>{!m.enabled&&<div className="notice">Independent mode is a test configuration. Joystick 2 X and Y control separate ailerons; this is not the default flight recommendation.</div>}
 <div className="grid2"><Panel title="Physical controller inputs" tag={<Pill>{demo?'INTERACTIVE SIMULATOR':'READ-ONLY'}</Pill>}><div className="panel-body" style={{position:'relative'}}>{!demo&&!f.inputs?<p className="copy" role="status">Controller inputs unknown</p>:<><div className="grid2"><Joystick x={f.inputs?.rudder??null} y={f.inputs?.elevator??null} label="Joystick 1" onMove={demo?(x,y)=>move({rudder:x,elevator:y}):undefined}/><Joystick x={f.inputs?.leftAileron??null} y={f.inputs?.rightAileron??null} label="Joystick 2" onMove={demo?(x,y)=>move({leftAileron:x,rightAileron:y}):undefined}/></div><div className="stack" style={{marginTop:25}}><Range label="Throttle slider · A6" value={input.throttle} disabled={!demo} onChange={v=>move({throttle:v})}/><div className="grid2"><Range label="Potentiometer 1 · A4" value={input.aux1} min={-1} disabled={!demo} onChange={v=>move({aux1:v})}/><Range label="Potentiometer 2 · A5" value={input.aux2} min={-1} disabled={!demo} onChange={v=>move({aux2:v})}/></div><div className="grid2"><Range label="Joystick 1 X · rudder" value={input.rudder} min={-1} disabled={!demo} onChange={v=>move({rudder:v})}/><Range label="Joystick 1 Y · elevator" value={input.elevator} min={-1} disabled={!demo} onChange={v=>move({elevator:v})}/><Range label="Joystick 2 X · roll / left" value={input.leftAileron} min={-1} disabled={!demo} onChange={v=>move({leftAileron:v})}/><Range label="Joystick 2 Y · right / common" value={input.rightAileron} min={-1} disabled={!demo} onChange={v=>move({rightAileron:v})}/></div></div><div className="controls-buttons">{['Mix ON','Mix OFF','Aux IN','Aux OUT'].map((label,i)=><Button key={label} disabled={!demo} variant={buttons[i]?'default':'outline'} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);push(i,true)}} onPointerUp={()=>push(i,false)} onPointerCancel={()=>push(i,false)} onKeyDown={e=>{if([' ','Enter'].includes(e.key)&&!e.repeat){e.preventDefault();push(i,true)}}} onKeyUp={e=>{if([' ','Enter'].includes(e.key))push(i,false)}}>{label}</Button>)}</div><div className="field-line"><span>Auxiliary direction <Pill>{demo?aux:'Unsupported'}</Pill></span><Button variant="ghost" size="sm" disabled={!demo} onClick={()=>setManual(null)}>Resume animation</Button></div><p className="copy">Mix ON/OFF latches. IN/OUT is momentary; neither or both means STOP. Demo motion expires after 500 ms. Hardware needs an independent onboard timeout.</p></>}</div></Panel>
 <Panel title="Aileron mixing" tag={<span className="eyebrow">COMMANDED POSITION</span>}><SurfaceView frame={f}/><fieldset disabled={!editable} className="panel-body stack"><div className="status-line mono"><span>L = common + roll</span><span>R = common − roll</span></div><Range label="Mix strength" value={m.strength} max={1.5} onChange={v=>update({strength:v})} disabled={!editable}/><Range label="Aileron differential" value={m.differential} max={.8} onChange={v=>update({differential:v})} disabled={!editable}/><div className="field-line"><div>Common / flaperon input<p className="muted text-xs">Joystick 2 Y is ignored by default in roll mode.</p></div><Switch aria-label="Enable common input" checked={m.common} disabled={!editable} onCheckedChange={v=>update({common:v})}/></div><div className="grid2">{(['leftAileron','rightAileron'] as Axis[]).map(a=><div className="field-line" key={a}><span>Reverse {a==='leftAileron'?'left':'right'}</span><Switch aria-label={`Reverse ${a}`} checked={m.channels[a].reverse} onCheckedChange={v=>setSettings(old=>({...old,mixer:{...old.mixer,version:old.mixer.version+1,channels:{...old.mixer.channels,[a]:{...old.mixer.channels[a],reverse:v}}}}))}/></div>)}</div>{Object.values(f.outputs).some(o=>o?.saturated)&&<div className="notice warning">Output saturation · commanded travel is clamped to limits.</div>}<p className="copy">Opposite physical deflection may need the same PWM direction because servo installations differ. Verify each direction with the propeller removed.</p><Button variant="outline" disabled={!demo} onClick={()=>{update({enabled:latchMix(m.enabled,true,true)});toast.info('Conflicting mix request ignored. Last confirmed mode retained.')}}>Test both mix buttons</Button></fieldset></Panel></div>
 <Panel title="Input → output mapping"><Table className="config-table"><TableHeader><TableRow>{['Physical control','Assignment','Raw ADC¹','Normalized','Output command','Aircraft pin'].map(v=><TableHead key={v}>{v}</TableHead>)}</TableRow></TableHeader><TableBody>{axes.map(a=><TableRow key={a}><TableCell>{assignment[a].input} <span className="muted">{assignment[a].pin}</span></TableCell><TableCell>{assignment[a].name}</TableCell><TableCell className="mono">{demo&&f.inputs?Math.round((a==='throttle'?f.inputs[a]:(f.inputs[a]+1)/2)*1023):'Unavailable'}</TableCell><TableCell className="mono">{fmt(f.inputs?.[a],3)}</TableCell><TableCell className="mono">{a.startsWith('aux')?'Not mapped':fmt(f.outputs[a]?.pwm,0)+' µs'}</TableCell><TableCell>{assignment[a].out}</TableCell></TableRow>)}</TableBody></Table><p className="panel-body copy">¹ Demo ADC values are reconstructed from simulated normalized inputs. Live raw ADC reporting requires firmware support. D7 is a proposed auxiliary output; additional functions remain unmapped.</p></Panel>
 <Panel title="Per-channel configuration" tag={<Choice label="Edit channel" value={axis} onChange={v=>setAxis(v as Axis)} options={axes.map(a=>({value:a,label:m.channels[a].name}))}/>}><fieldset disabled={!editable} className="panel-body stack"><div className="grid2"><label className="field">Channel name<input value={c.name} maxLength={60} onChange={e=>channel({name:e.target.value})}/></label><div className="field-line"><span>Reverse output</span><Switch aria-label="Channel reversal" checked={c.reverse} onCheckedChange={v=>channel({reverse:v})}/></div></div><div className="grid3"><NumberField label="Minimum · µs" value={c.min} min={750} max={c.center-1} onChange={v=>channel({min:v})}/><NumberField label="Center · µs" value={c.center} min={c.min+1} max={c.max-1} onChange={v=>channel({center:v})}/><NumberField label="Maximum · µs" value={c.max} min={c.center+1} max={2250} onChange={v=>channel({max:v})}/><Range label="Deadband" value={c.deadband} max={.2} onChange={v=>channel({deadband:v})}/><Range label="Expo" value={c.expo} onChange={v=>channel({expo:v})}/><Range label="Rate" value={c.rate} max={1.5} onChange={v=>channel({rate:v})}/><Range label="Trim" value={c.trim} min={-.3} max={.3} onChange={v=>channel({trim:v})}/><NumberField label="Subtrim · µs" value={c.subtrim} min={-150} max={150} onChange={v=>channel({subtrim:v})}/></div><div className="button-row"><Button onClick={()=>void p.save()}>Save requested configuration</Button><Button variant="outline" disabled={!demo} onClick={()=>move({...zeroInputs})}>Preview neutral</Button></div><p className="copy">Minimum and maximum are hard limits. Saving web configuration does not confirm hardware application. In-flight mixing changes require explicitly supported and tested firmware transition rules.</p></fieldset></Panel></div>
}
