import {useEffect,useState} from 'react';
import {AlertTriangle,AudioLines,LockKeyhole,ShieldCheck,Volume2,VolumeX} from 'lucide-react';
import {Button} from './ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from './ui/dialog';
import {Switch} from './ui/switch';
import {Panel} from './instruments';
import {Choice,Pill} from './controls';
import type {WorkspaceProps} from './flight-deck';
import type {VoiceController} from '../hooks/use-voice-announcements';
import {voiceCategories} from '../lib/announcements';
import {parachuteRejection,recoveryLabel,sanitizeSafety,readyForTakeoff,freshFrame} from '../lib/safety';

export type RecoveryActions={open:boolean;setOpen:(open:boolean)=>void;deploy:(guard:boolean)=>string|null;reset:()=>void};
export function Canopy({deployed=false}:{deployed?:boolean}){
  return <svg viewBox="0 0 260 200" className={`canopy ${deployed?'canopy-deployed':''}`} role="img" aria-label={deployed?'Illustration of deployed parachute':'Parachute recovery illustration'}>
    <circle cx="130" cy="96" r="83" fill="none" stroke="currentColor" opacity=".12"/>
    <path d="M45 88a85 65 0 0 1 170 0q-22-14-43 0q-21-14-42 0q-21-14-42 0q-22-14-43 0Z" fill="currentColor" fillOpacity={deployed?'.19':'.07'} stroke="currentColor" strokeWidth="2"/>
    <path d="M130 23Q87 35 88 88m42-65q43 12 42 65M45 88l76 68M88 88l37 68m47-68-37 68m80-68-76 68m-9-133v65" fill="none" stroke="currentColor" strokeWidth="1.3" opacity=".65"/>
    <path d="m130 141-5 17-32 12v5l32-4v11l-9 6v3l14-3 14 3v-3l-9-6v-11l32 4v-5l-32-12Z" fill="currentColor"/>
  </svg>;
}
function recoveryContext(p:WorkspaceProps,guardOpen=false){return {environment:p.environment,frame:p.frame,capabilities:p.capabilities,now:p.now,role:p.account.role,authenticated:p.account.authenticated,guardOpen,deployed:p.frame.safety?.parachute?.state==='deployed'};}
export function RecoveryDialog({p,actions}:{p:WorkspaceProps;actions:RecoveryActions}){
  const [guard,setGuard]=useState(false),[error,setError]=useState('');
  useEffect(()=>{setGuard(false);setError('');},[actions.open,p.environment,p.settings.id,p.frame.bootId]);
  const rejection=parachuteRejection(recoveryContext(p,guard));
  return <Dialog open={actions.open} onOpenChange={actions.setOpen}><DialogContent className="recovery-dialog"><DialogHeader><DialogTitle>Parachute recovery</DialogTitle><DialogDescription>{p.environment==='DEMO'?'Guarded simulator action. No aircraft command is sent.':p.environment==='REPLAY'?'Recorded status only. All recovery actions are disabled.':'An internet request cannot guarantee delivery or deployment.'}</DialogDescription></DialogHeader>
    <div className="recovery-target"><span className="eyebrow">TARGET AIRCRAFT</span><strong>{p.settings.name} <span className="mono muted">/ {p.settings.id}</span></strong><Pill tone={p.environment==='DEMO'?'warning':'muted'}>{p.environment}</Pill></div>
    <div className="status-line"><span>Reported recovery status</span><strong>{recoveryLabel(p.frame,p.capabilities,p.now)}</strong></div>
    {p.environment==='DEMO'?<><label className={`recovery-cover ${guard?'is-open':''}`}><input type="checkbox" checked={guard} disabled={p.frame.safety?.parachute?.state==='deployed'} onChange={e=>setGuard(e.target.checked)}/><LockKeyhole size={20}/><span>Lift the protective cover<small>Then confirm deployment in the simulator.</small></span></label><Button variant="destructive" size="lg" disabled={!!rejection} onClick={()=>{const reason=actions.deploy(guard);setError(reason??'');setGuard(false);}}>Simulate parachute deployment</Button></>:<Button variant="destructive" disabled>Live deployment unavailable</Button>}
    <p className="copy" role="status">{error||rejection||'Confirmation applies once, to this simulator aircraft only.'}</p>
    <div className="notice recovery-caution"><AlertTriangle size={18}/><span>Independent transmitter activation and aircraft-specific recovery logic must run onboard. No parachute hardware, output pin, or deployment envelope has been configured here.</span></div>
  </DialogContent></Dialog>;
}
export function SafetyWorkspace({p,voice,actions}:{p:WorkspaceProps;voice:VoiceController;actions:RecoveryActions}){
  const fresh=freshFrame(p.frame,p.now),safety=fresh?sanitizeSafety(p.frame,p.capabilities):null,status=recoveryLabel(p.frame,p.capabilities,p.now),deployed=safety?.parachute?.state==='deployed';
  const supported=p.capabilities?.features.parachute===true;
  const voices=voice.voices.map(v=>({value:v.voiceURI,label:`${v.name} · ${v.lang}${v.localService?' · on device':''}`}));
  if(voice.preferences.voiceURI&&!voices.some(v=>v.value===voice.preferences.voiceURI))voices.push({value:voice.preferences.voiceURI,label:'Saved voice unavailable · using default'});
  return <div className="stack"><div className="grid2 safety-grid"><Panel title="Emergency recovery" tag={<Pill tone={p.environment==='DEMO'?'warning':'muted'}>{p.environment==='DEMO'?'SIMULATOR':p.environment==='REPLAY'?'REPLAY · NO CONTROL':'LIVE DISPATCH DISABLED'}</Pill>}><div className="panel-body"><div className="recovery-hero"><Canopy deployed={deployed}/><div><div className="eyebrow">PARACHUTE SYSTEM</div><h2>{status}</h2><p className="copy">{p.environment==='DEMO'?'Practice a guarded recovery request. The illustration is a status display; it does not simulate descent or motor behavior.':'Activation and recovery must be implemented and validated onboard before a live request can be enabled.'}</p></div></div><div className="button-row"><Button variant={deployed?'outline':'destructive'} onClick={()=>actions.setOpen(true)}><ShieldCheck size={17}/>{p.environment==='DEMO'?'Open recovery guard':'Review recovery availability'}</Button>{p.environment==='DEMO'&&deployed&&<Button variant="outline" onClick={actions.reset}>Reset recovery simulation</Button>}</div><div className="health-row"><span>Firmware capability</span><span>{supported?p.environment==='DEMO'?'Simulator only':'Reported supported':p.capabilities?'Unsupported':'Unknown'}</span></div><div className="health-row"><span>Deployment feedback</span><span>{!fresh?'Unknown / stale':safety?.parachute?.feedback==='deployment_sensor'?p.environment==='DEMO'?'Simulated sensor':'Reported sensor':'Not reported'}</span></div><div className="health-row"><span>Output mapping</span><span className="muted">Not mapped</span></div><p className="copy">Sent → Accepted → Applied tracks a command. Only a supported deployment sensor can confirm deployment. A dashboard disconnection leaves delivery uncertain.</p></div></Panel>
    <Panel title="Voice announcements" tag={<AudioLines size={18} className="good"/>}><div className="panel-body stack"><div className="status-line"><span>{!voice.supported?'Speech unavailable in this browser':voice.error?'Voice needs attention · see message below':voice.active?'Voice enabled in this tab':voice.preferences.enabled?'Resume voice for this tab':'Voice is off'}</span><Pill tone={voice.error?'warning':voice.active?'good':'muted'}>BROWSER AUDIO</Pill></div><div className="button-row"><Button disabled={!voice.supported} onClick={voice.active?voice.mute:voice.enable}>{voice.active?<VolumeX size={17}/>:<Volume2 size={17}/>} {voice.active?'Mute voice':voice.preferences.enabled?'Resume voice':'Enable voice'}</Button><Button variant="outline" disabled={!voice.supported} onClick={()=>voice.preview()}>Test voice</Button><Button variant="ghost" disabled={!voice.supported} onClick={voice.stop}>Stop speaking</Button></div><Choice label="Voice" value={voice.preferences.voiceURI||'__system__'} onChange={voiceURI=>voice.update({voiceURI:voiceURI==='__system__'?'':voiceURI})} options={[{value:'__system__',label:'System default · English'},...voices]}/><label className="field">Volume · {Math.round(voice.preferences.volume*100)}%<input type="range" min="0" max="1" step=".05" value={voice.preferences.volume} onChange={e=>voice.update({volume:Number(e.target.value)})}/></label><label className="field">Speaking rate · {voice.preferences.rate.toFixed(1)}×<input type="range" min=".7" max="1.4" step=".1" value={voice.preferences.rate} onChange={e=>voice.update({rate:Number(e.target.value)})}/></label><p className="copy voice-local">Preferences save on this browser. Enable audio after opening a new tab. These are browser announcements, separate from the transmitter buzzer. Sound depends on browser, device volume, and tab availability.</p>{voice.error&&<p className="warning copy" role="alert">{voice.error}</p>}</div></Panel></div>
    <div className="grid2"><Panel title="Announcement rules" tag={<Pill>{p.environment==='REPLAY'?'REPLAY SILENT':'EVENT DRIVEN'}</Pill>}><div className="panel-body">{Object.entries(voiceCategories).map(([key,label])=><div className="field-line" key={key}><label htmlFor={`voice-${key}`}>{label}</label><Switch id={`voice-${key}`} checked={voice.preferences.categories[key as keyof typeof voiceCategories]} onCheckedChange={v=>voice.update({categories:{...voice.preferences.categories,[key]:v}})}/></div>)}<p className="copy">Only changes are announced. Critical alerts interrupt routine speech; old or resolved messages are discarded. Demo announcements begin with “Demo.” Replay never triggers automatic announcements.</p><div className="button-row"><Button variant="outline" disabled={!voice.supported} onClick={()=>voice.preview('Connection lost. Aircraft condition unknown.')}>Preview connection alert</Button><Button variant="outline" disabled={!voice.supported} onClick={()=>voice.preview('Flight failure reported.')}>Preview failure alert</Button></div></div></Panel>
    <Panel title="Readiness & announcement history"><div className="panel-body"><div className="health-row"><span>Flight failure</span><span className={safety?.flightFailure===true?'critical':'muted'}>{!fresh?'Unknown / stale':safety?.flightFailure===true?'Reported':safety?.flightFailure===false?'Not reported as failed':'Unsupported / unknown'}</span></div><div className="health-row"><span>Takeoff readiness</span><span className="muted">{(p.environment!=='LIVE'||p.backend)&&readyForTakeoff(p.frame,p.settings,p.capabilities,p.now)?p.environment==='DEMO'?'Ready · simulator':'Firmware report + checks':'Not confirmed'}</span></div><p className="copy">A lost connection is announced as lost communication. Flight failure requires an explicit supported firmware report. “Ready for takeoff” requires an explicit firmware readiness report, all six operator checks, fresh healthy links and IMU, low throttle, disarmed state, and both batteries above warning.</p><div className="voice-history" aria-live="polite">{voice.history.length?voice.history.map((n,i)=><div className="event" key={`${n.key}:${n.at}:${i}`}><time>{new Date(n.at).toLocaleTimeString()}</time><p>{n.text}</p></div>):<p className="copy">No announcements in this aircraft environment yet.</p>}</div></div></Panel></div></div>;
}
